# config/secrets.yml
production:
  secret_key_base: <%= ENV["SECRET"] %>
  aws_secret: banana
  some_password: clear2023
development:
  secret_key_base: ac232425t
  aws_secret: clear2023
test:
  secret_key_base: 56tr4321
#not_indented: key for all env in once
secret_key_base: <%= ENV["SECRET"] %>
